### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by Gwemox** [laminas/laminas-xmlrpc#18]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         |no
| BC Break    | no

#### Summary

Support PHP 8.1

**Comment by tobias-trozowski** [comment]
@froschdesign `laminas-xmlrpc` requires `laminas-xml` (which is considered security-only), how can this be handled?
Is PHP 8.1 support for `laminas-xml` considered as new feature or "security update"?

**Comment by froschdesign** [comment]
@tobias-trozowski 
> Is PHP 8.1 support for `laminas-xml` considered as new feature or "security update"?

We can create a new minor release for laminas-xml with the support for PHP 8.1.

**Comment by tobias-trozowski** [comment]
@froschdesign ok, so i guess i'm gonna start there
