### ISSUE TITLE
Provide PHP 8.1 support

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-xmlrpc#21]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Add `~8.1.0` to the list of allowed PHP constraints, and ensure that the test pass without any deprecation messages.

**Comment by Ocramius** [comment]
Already provided in `2.12.0`: https://github.com/laminas/laminas-xmlrpc/blob/15849ccd9bb479ebe63ca3a6614930eda1ed33eb/composer.json#L24

**Comment by weierophinney** [comment]
Yep, just discovered that.

Forgot it was one of the early ones we tackled. :)
