### ISSUE TITLE
Casting a bool to an int will make false true

### ISSUE THREAD

**Issue by SuperDJ** [laminas/laminas-xmlrpc#26]
On 
https://github.com/laminas/laminas-xmlrpc/blob/feb29f648d642be441cc799a6167896c7c3f98a1/src/Value/Boolean.php#L18
a boolean is cast to an integer. This introduces a problem that `false` is cast to `1` instead of `0`. This is also described in the docs [here](https://www.php.net/manual/en/language.types.boolean.php). My suggestion would be to use `filter_var($value, FILTER_VALIDATE_BOOLEAN)` instead.

**Comment by Ocramius** [comment]
@SuperDJ not clear to me why that is a problem: can you provide a failing test case?

**Comment by Ocramius** [comment]
Handled in #28
