### ISSUE TITLE
Declaration of Laminas\XmlRpc\Server::getFunctions not compatible

### ISSUE THREAD

**Issue by SuperDJ** [laminas/laminas-xmlrpc#32]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | laminas/laminas-xmlrpc 2.15.0,  laminas/laminas-server: 2.13.0|

#### Summary

I'm not quite sure if this is an issue on my side. If it is please ignore/ close the issue. But I'm getting the following error message:
>Declaration of Laminas\XmlRpc\Server::getFunctions() must be compatible with Laminas\Server\AbstractServer::getFunctions():

#### Current behavior

It now gives an error:

Declaration of Laminas\XmlRpc\Server::getFunctions() must be compatible with Laminas\Server\AbstractServer::getFunctions(): Laminas\Server\Definition {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Declaration of Laminas\\XmlRpc\\Server::getFunctions() must be compatible with Laminas\\Server\\AbstractServer::getFunctions(): Laminas\\Server\\Definition at /vendor/laminas/laminas-xmlrpc/src/Server.php:494)

#### Expected behavior

Declaration of Laminas\XmlRpc\Server::getFunctions() is compatible with Laminas\Server\AbstractServer::getFunctions()

**Comment by Ocramius** [comment]
`laminas/laminas-server: 2.13.0` was removed from packagist some hours after its release: it was completely broken.

See https://github.com/laminas/laminas-server/issues/62

Please either downgrade or upgrade to `laminas-/laminas-server:2.13.1`

**Comment by SuperDJ** [comment]
@Ocramius yes, I can confirm that updating (now `laminas-/laminas-server:2.14.0`) fixed the issue
