### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-xmlrpc#8]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

To be prepared for the december release of PHP 8.0, this repository has some additional TODOs to be tested against the new major version.

In order to make this repository compatible, one has to follow these steps:

- [x] Modify `composer.json` to provide support for PHP 8.0 by adding the constraint `~8.0.0`
- [x] Modify `composer.json` to drop support for PHP less than 7.3
- [x] Modify `composer.json` to implement phpunit 9.3 which supports PHP 7.3+
- [x] Modify `.travis.yml` to ignore platform requirements when installing composer dependencies (simply add `--ignore-platform-reqs` to `COMPOSER_ARGS` env variable)
- [x] Modify `.travis.yml` to add PHP 8.0 to the matrix (*NOTE*: Do not allow failures as PHP 8.0 has a feature freeze since 2020-08-04!)
- [x] Modify source code in case there are incompatibilities with PHP 8.0

**Comment by dwightwatson** [comment]
Had a look at this, but appears it's dependent on `laminas-http` supporting PHP 8.0 as well. Looks like there's an [issue](https://github.com/laminas/laminas-http/issues/44) and [open pull request](https://github.com/laminas/laminas-http/pull/45) for it.

**Comment by tvlooy** [comment]
laminas-http is compatible with php 8 now but laminas-math is also an issue and needs to be compatible first. There is an open PR for it https://github.com/laminas/laminas-math/pull/5
